### ISSUE TITLE
Komenda !top10 nic nie zwraca

### ISSUE THREAD

**Issue by proofek** [proofek/cwiczymy-razem-bot#30]
Po zmianie query i dodaniu warunku removed=false komenda nic nie zwaraca

**Comment by proofek** [comment]
Error: 9 FAILED_PRECONDITION: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/bazok-dev/firestore/indexes?create_composite=Cklwcm9qZWN0cy9iYXpvay1kZXYvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3Jlc3VsdHMvaW5kZXhlcy9fEAEaCwoHcmVtb3ZlZBABGg0KCXNlYXNvbnN1bRACGgwKCF9fbmFtZV9fEAI
    at Object.callErrorFromStatus (C:\Users\sebma\OneDrive\Documents\Dev\cwiczymy-razem-bot\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (C:\Users\sebma\OneDrive\Documents\Dev\cwiczymy-razem-bot\node_modules\@grpc\grpc-js\build\src\client.js:327:49)
    at Object.onReceiveStatus (C:\Users\sebma\OneDrive\Documents\Dev\cwiczymy-razem-bot\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:305:181)
    at C:\Users\sebma\OneDrive\Documents\Dev\cwiczymy-razem-bot\node_modules\@grpc\grpc-js\build\src\call-stream.js:124:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Caused by: Error
    at Query._get (C:\Users\sebma\OneDrive\Documents\Dev\cwiczymy-razem-bot\node_modules\@google-cloud\firestore\build\src\reference.js:1472:23)
    at Query.get (C:\Users\sebma\OneDrive\Documents\Dev\cwiczymy-razem-bot\node_modules\@google-cloud\firestore\build\src\reference.js:1461:21)
    at Function.findTop10 (C:\Users\sebma\OneDrive\Documents\Dev\cwiczymy-razem-bot\user.js:353:8)
    at module.exports (C:\Users\sebma\OneDrive\Documents\Dev\cwiczymy-razem-bot\commands\top10.js:8:8)
    at module.exports (C:\Users\sebma\OneDrive\Documents\Dev\cwiczymy-razem-bot\events\message.js:56:12)
    at Client.<anonymous> (C:\Users\sebma\OneDrive\Documents\Dev\cwiczymy-razem-bot\index.js:22:39)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\sebma\OneDrive\Documents\Dev\cwiczymy-razem-bot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\sebma\OneDrive\Documents\Dev\cwiczymy-razem-bot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\sebma\OneDrive\Documents\Dev\cwiczymy-razem-bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31) {
  code: 9,
  details: 'The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/bazok-dev/firestore/indexes?create_composite=Cklwcm9qZWN0cy9iYXpvay1kZXYvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3Jlc3VsdHMvaW5kZXhlcy9fEAEaCwoHcmVtb3ZlZBABGg0KCXNlYXNvbnN1bRACGgwKCF9fbmFtZV9fEAI',
  metadata: Metadata { internalRepr: Map {}, options: {} }
}

**Comment by proofek** [comment]
Trzeba było stworzyć brakujące indeksy. Dodałem projekt firebase, żeby na przyszłość można było deployować zmiany do bazy.
